In [2]:
import pandas as pd
from collections import Counter
orgdata = pd.read_csv("FeaturedBookstoreNew.csv")
orgdata.head()

,name,representImage,intro,address,longitude,latitude,openTime,phone,email,headCityName,cityName,groupTypeName,seg,city
0,人生書局,http://cloud.culture.tw/e_new_upload/cms/image...,位在鹽埕區的新樂街上，看守著台灣戰後的歷史。早年人生書局只賣自己出版的書籍，是個相當「冷門」...,新樂街145號,120.281814,22.620168,一～日｜09:00 - 21:00,NaN,NaN,NaN,高雄市 鹽埕區,實體書店,"['鹽埕區', '新樂街', '台灣', '戰後', '歷史', '人生書局', '只賣',...",高雄市
1,一本書店,http://cloud.culture.tw/e_new_upload/cms/image...,位於台中文創園區對面的一本書店，與許多手作文創產業合作，在店內會舉辦教學課程。時常舉辦新詩朗...,復興路3段348巷2-2號1樓,120.679643,24.132733,三～日｜12:00 - 17:00,NaN,NaN,NaN,臺中市 南區,實體書店,"['書籍', '創園區', '對面', '書店', '許多手', '創產業', '內會', ...",臺中市
2,書集喜室,http://cloud.culture.tw/e_new_upload/cms/image...,隱身在鹿港巷弄中的書集喜室，是一間二手書店，原本一棟快要廢棄的日治時期老屋，被店主買下，經過...,彰化縣鹿港鎮杉行街20號,120.435059,24.057213,週三至週日11:00-17:30,NaN,NaN,NaN,彰化縣 鹿港鎮,實體書店,"['喜室', '書集', '茶屋', '隱身', '巷弄', '一間', '二手書', '一...",彰化縣
3,樸食小舖,http://cloud.culture.tw/e_new_upload/cms/image...,樸食小舖，我們是「市集裡的書店」!\r\n\r\n我們原先在新竹市開有機複合餐廳，後來移居苗...,新竹市光復路二段101號(清大成功湖邊),120.969102,24.806942,每月第一周和第三周的周六，早上九點到下午兩點,NaN,nicole571105@gmail.com,竹蜻蜓綠市集,新竹市 新竹市,實體書店,"['書店', '樸食小舖', '市集裡', '沒有', '大門', '市集', '有機複合餐...",新竹市
4,小陽。日栽書屋,http://cloud.culture.tw/e_new_upload/cms/image...,一點勇氣將小陽。春日子更明確蛻變成小陽。日栽書屋，走過那段和伙伴一起的充滿春分生命力的日子，...,屏東市中山路清營巷1號,120.501205,22.677970,週四至週日 14:00-20:00,NaN,ssunville@hotmail.com,NaN,屏東縣 屏東市,實體書店,"['小陽', '一點', '勇氣將', '更明確', '蛻變', '日栽書屋', '走過',...",屏東縣

In [3]:
subdata = orgdata[['city', 'seg']]

In [4]:
output_series = subdata.groupby(['city'])['seg'].apply(lambda x: ','.join(x)).reset_index()

In [6]:
output_series

   city                                                seg
0   南投縣  ['空間', '這個', 'books', '分享', '書店', '時間', '交會', ...
1   嘉義市  ['書籍', '位處', '嘉義', '陳列', '繪本', '建築', '飲食', '文學...
2   嘉義縣  ['仁偉書局', '主理', '嘉義民雄', '將近', '40', '歷史', '返鄉',...
3   宜蘭縣  ['書店', '空間', '黑潮', '文化', '烏石港', '遊客', '二樓', '范...
4   屏東縣  ['小陽', '一點', '勇氣將', '更明確', '蛻變', '日栽書屋', '走過',...
5   彰化縣  ['喜室', '書集', '茶屋', '隱身', '巷弄', '一間', '二手書', '一...
6   新北市  ['地區', '八里', '書店', '店內', '詩集', '身心靈', '文學', '書...
7   新竹市  ['書店', '樸食小舖', '市集裡', '沒有', '大門', '市集', '有機複合餐...
8   新竹縣  ['書店', '閱讀', '文化', '多元', '蔬食', '竹北', '園區', '親子...
9   桃園市  ['台灣', '漫畫', '兼售', '桃園', '邊的', '書店', '及繪本', '主...
10  澎湖縣  ['空間', '教學', '風向', '展覽', '手作', '二手書', '找個', '來...
11  臺中市  ['書籍', '創園區', '對面', '書店', '許多手', '創產業', '內會', ...
12  臺北市  ['重慶', '書店', '販售', '書局', '南路', '創辦', '紅屋', '書街...
13  臺南市  ['書籍', '擁有', '五萬冊', '豐富', '文學', '絕版', '雜誌', '空...
14  臺東縣  ['食冊', '書店', '結合', '咖啡', '心靈', '糧食', '三個', '來台...
15  花蓮縣  ['書店', '醫師', '懶人', '並且', '花蓮', '民眾', '閱讀', '店名...
16  苗栗縣  ['書店', '苗栗', '苗栗人', '苗栗市', '日榮本', '屋位', '火車', ...
17  金門縣  ['金門', '二手書', '首間', '經營', '書籍', '買賣', '點心', '長...
18  高雄市  ['鹽埕區', '新樂街', '台灣', '戰後', '歷史', '人生書局', '只賣',...

In [7]:
output_series['seg'] = output_series['seg'].str.replace("', '", " ")
output_series

   city                                                seg
0   南投縣  ['空間 這個 books 分享 書店 時間 交會 讀書 聚會 愉悅 時光 成長 變老 回顧...
1   嘉義市  ['書籍 位處 嘉義 陳列 繪本 建築 飲食 文學 為主 空間 几淨 並在 擺設 發揮 食類...
2   嘉義縣  ['仁偉書局 主理 嘉義民雄 將近 40 歷史 返鄉 堅持 不關 閉書區 更導入 經營 思維...
3   宜蘭縣  ['書店 空間 黑潮 文化 烏石港 遊客 二樓 范特喜 微創 型態 開放 企圖 閱覽區 服務...
4   屏東縣  ['小陽 一點 勇氣將 更明確 蛻變 日栽書屋 走過 充滿 延續 發光 發熱 期許 將帶給 ...
5   彰化縣  ['喜室 書集 茶屋 隱身 巷弄 一間 二手書 一棟 廢棄 日治 時期 買下 經過 模樣 進...
6   新北市  ['地區 八里 書店 店內 詩集 身心靈 文學 書種 店外 風景 簡單 輕食 閱讀 提供 雅...
7   新竹市  ['書店 樸食小舖 市集裡 沒有 大門 市集 有機複合餐廳 公館 鄉間 展開 兩人六貓 四狗...
8   新竹縣  ['書店 閱讀 文化 多元 蔬食 竹北 園區 親子 共讀 導入 專業 選書 選品 選食 引領...
9   桃園市  ['台灣 漫畫 兼售 桃園 邊的 書店 及繪本 主題 選書 二手書 閱讀 適合 晃悠 喝杯 ...
10  澎湖縣  ['空間 教學 風向 展覽 手作 二手書 找個 來份 度過 時光 這也 畫室 藝術 膨風 圖...
11  臺中市  ['書籍 創園區 對面 書店 許多手 創產業 內會 舉辦 教學課程 時常舉 新詩朗讀會 餐點...
12  臺北市  ['重慶 書店 販售 書局 南路 創辦 紅屋 書街 風景 中極具 過去 出版品 現今 特選 ...
13  臺南市  ['書籍 擁有 五萬冊 豐富 文學 絕版 雜誌 空間 並特別 設置 蒐集 所妝點 童書區 歡...
14  臺東縣  ['食冊 書店 結合 咖啡 心靈 糧食 三個 來台 東合創 綜合 身心靈 養分 進來點 剛剛...
15  花蓮縣  ['書店 醫師 懶人 並且 花蓮 民眾 閱讀 店名 誕生 約定 因緣際會 開始 這位 經營 ...
16  苗栗縣  ['書店 苗栗 苗栗人 苗栗市 日榮本 屋位 火車 一棟 內部 舊時代 裝潢 經營 獨立 較...
17  金門縣  ['金門 二手書 首間 經營 書籍 買賣 點心 長期 徵求 換宿 圖片 臉書 粉絲 專頁 台...
18  高雄市  ['鹽埕區 新樂街 台灣 戰後 歷史 人生書局 只賣 書籍 相當 冷門 書店 佛經 參考書 ...

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

docs = output_series['seg'].tolist()
vec = CountVectorizer()
X = vec.fit_transform(docs)
df = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())
df

C:\Users\USER\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,11,117,12,14,15,16,18,1932,1954,1955,...,鹽埕區,鹿港,黎明,黑潮,黑膠,點心,點杯,點的,點點,鼓勵
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
6,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,3,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,0
12,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,2,1,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,2,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
15,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
18,0,0,0,0,0,1,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [9]:
coocc = df.T.dot(df)
coocc

,11,117,12,14,15,16,18,1932,1954,1955,...,鹽埕區,鹿港,黎明,黑潮,黑膠,點心,點杯,點的,點點,鼓勵
11,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,2,1,0,0,0,0
117,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,2,1,0,0,0,0
12,1,1,6,3,0,2,0,2,1,2,...,0,0,0,0,2,1,0,0,0,0
14,0,0,3,16,3,1,0,1,0,1,...,0,0,3,0,0,3,3,0,0,0
15,0,0,0,3,2,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
點心,1,1,1,3,1,1,0,0,1,0,...,0,0,1,0,2,3,1,0,0,0
點杯,0,0,0,3,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,0
點的,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
點點,0,0,0,0,0,1,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
鼓勵,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [10]:
import plotly.express as px

In [ ]:
px.imshow(coocc)

In [12]:
result = coocc.values.flatten()

In [13]:
fig = px.histogram(result)

In [ ]:
fig.show()

In [15]:
import numpy as np

filter_num = 200
getid = coocc.index
important = pd.DataFrame(columns = getid).T
important['relation'] = ""
subcoocc = coocc
dropid = []

for i in range(len(coocc)):
    result = coocc[coocc.iloc[i] > filter_num].index.tolist()    
    if(len(result) > 0):
        important['relation'].loc[getid[i]] = coocc[coocc.iloc[i] > filter_num].index.tolist()
    else:
        dropid.append(i)
        important = important.drop([getid[i]])
        subcoocc = subcoocc.drop([getid[i]])

In [61]:
subcoocc

,11,117,12,14,15,16,18,1932,1954,1955,...,鹽埕區,鹿港,黎明,黑潮,黑膠,點心,點杯,點的,點點,鼓勵
協會,5,5,19,32,6,20,3,6,5,6,...,2,1,5,1,10,11,5,1,2,3
台灣,8,8,23,41,8,24,7,6,8,6,...,5,1,7,1,16,16,7,1,5,3
圖片,5,5,19,32,6,20,3,6,5,6,...,2,1,5,1,10,11,5,1,2,3
店內,7,7,7,13,5,8,4,0,7,0,...,2,2,3,0,14,10,3,2,2,0
建構,5,5,19,32,6,20,3,6,5,6,...,2,1,5,1,10,11,5,1,2,3
建立,5,5,19,32,6,20,3,6,5,6,...,2,1,5,1,10,11,5,1,2,3
文化,8,8,23,33,6,20,3,6,8,6,...,2,1,5,1,16,14,5,1,2,3
日期,5,5,19,32,6,20,3,6,5,6,...,2,1,5,1,10,11,5,1,2,3
書店,22,22,35,42,9,21,10,5,22,5,...,4,1,8,1,44,30,8,1,4,3
書籍,12,12,19,26,6,15,8,2,12,2,...,6,1,5,1,24,18,5,1,6,0
空間,8,8,14,23,5,9,0,3,8,3,...,0,0,5,2,16,13,5,0,0,1
閱讀,10,10,26,42,8,22,5,6,10,6,...,3,1,7,1,20,18,7,1,3,3

In [62]:
subcoocc.columns[dropid]

Index(['11', '117', '12', '14', '15', '16', '18', '1932', '1954', '1955',
       ...
       '鹽埕區', '鹿港', '黎明', '黑潮', '黑膠', '點心', '點杯', '點的', '點點', '鼓勵'],
      dtype='object', length=2382)

In [16]:
subcoocc.drop(subcoocc.columns[dropid], axis=1, inplace=True)
subcoocc

     協會   台灣   圖片   店內   建構   建立   文化   日期   書店   書籍   空間   閱讀
協會  131  170  131   70  131  131  149  131  236  137  103  181
台灣  170  235  170  107  170  170  198  170  346  209  139  247
圖片  131  170  131   70  131  131  149  131  236  137  103  181
店內   70  107   70   78   70   70   91   70  210  127   79  117
建構  131  170  131   70  131  131  149  131  236  137  103  181
建立  131  170  131   70  131  131  149  131  236  137  103  181
文化  149  198  149   91  149  149  178  149  308  177  129  219
日期  131  170  131   70  131  131  149  131  236  137  103  181
書店  236  346  236  210  236  236  308  236  689  381  253  399
書籍  137  209  137  127  137  137  177  137  381  240  141  229
空間  103  139  103   79  103  103  129  103  253  141  117  161
閱讀  181  247  181  117  181  181  219  181  399  229  161  282

In [ ]:
px.imshow(subcoocc)